addReviewers: true
addAssignees: author
useReviewGroups: true

reviewGroups:
  groupA:
    - leonraz58
    - Pumpkin-Pie93
    - apelsinom
    - olesya-sh-dev

numberOfReviewers: 4
useAssigneeGroups: false

skipKeywords:
  - wip
  - WIP