name: 'Auto Assign Dev'
on:
  pull_request:
    types: [opened, reopened]
    branches:
      - dev

permissions:
  pull-requests: write
  contents: write

jobs:
  add-reviews:
    runs-on: ubuntu-latest
    steps:
      - uses: kentaro-m/auto-assign-action@v2.0.0